In [ ]:
import numpy as np
import pandas as pd
import json

:

In [2]:
# Load the JSON file
with open('linkedIn_data.json', 'r') as file:
    data = json.load(file)

# Flatten and normalize nested JSON structures
df_profiles = pd.json_normalize(data)

# Show the first few rows
print(df_profiles.head())
df_profiles

                                     id vanityName  \
0                          abcdef123456   john-doe
1  8923110b-1554-4a4c-be20-1deb2e232103        NaN
2  8923110b-1554-4a4c-be20-1deb2e232103        NaN

                                    publicProfileUrl  \
0               https://www.linkedin.com/in/john-doe
1                                                NaN
2  https://www.linkedin.com/in/amanda-gonzalez-89...

                            industry  \
0  Information Technology & Services
1  Information Technology & Services
2  Information Technology & Services

                                      certifications  \
0  [{'name': 'AWS Certified Machine Learning - Sp...
1  [{'name': 'AWS Certified Machine Learning – Sp...
2  [{'name': 'AWS Certified Machine Learning – Sp...

                                           languages  followers  total_posts  \
0  [{'name': 'English', 'proficiency': 'Native'},...       1053            3
1  [{'name': 'English', 'proficiency': 'Native'},...       1890            2
2  [{'name': 'English', 'proficiency': 'Native'},...       1890            2

                                               posts  \
0  [{'post_id': 'urn:li:ugcPost:1111111', 'conten...
1  [{'post_id': 'urn:li:ugcPost:3350334', 'conten...
2  [{'post_id': 'urn:li:ugcPost:3350334', 'conten...

  firstName.localized.en_US  ... location.postalCode  \
0                      John  ...               94043
1                    Amanda  ...               45211
2                    Amanda  ...               45211

     location.geographicArea  \
0  Mountain View, California
1    South Joel, Connecticut
2    South Joel, Connecticut

                             summary.localized.en_US  \
0  Experienced Data Scientist with a passion for ...
1                                                NaN
2                                                NaN

                                  positions.elements  \
0  [{'title': 'Senior Data Scientist', 'company':...
1  [{'title': 'Software Developer', 'company': {'...
2  [{'title': 'Software Developer', 'company': {'...

                                  education.elements  \
0  [{'schoolName': 'Stanford University', 'degree...
1  [{'schoolName': 'MIT', 'degreeName': 'Master o...
2  [{'schoolName': 'MIT', 'degreeName': 'Master o...

                                     skills.elements  \
0  [{'name': {'localized': {'en_US': 'Machine Lea...
1  [{'name': {'localized': {'en_US': 'Data Visual...
2  [{'name': {'localized': {'en_US': 'Data Visual...

  posts_summary.total_likes posts_summary.total_comments  \
0                       472                           83
1                       724                           85
2                       724                           85

  posts_summary.total_shares  \
0                         36
1                         47
2                         47

                                             summary
0                                                NaN
1  Wish bar above medical role defense task. Fath...
2  Wish bar above medical role defense task. Fath...

[3 rows x 24 columns]

,id,vanityName,publicProfileUrl,industry,certifications,languages,followers,total_posts,posts,firstName.localized.en_US,...,location.postalCode,location.geographicArea,summary.localized.en_US,positions.elements,education.elements,skills.elements,posts_summary.total_likes,posts_summary.total_comments,posts_summary.total_shares,summary
0,abcdef123456,john-doe,https://www.linkedin.com/in/john-doe,Information Technology & Services,[{'name': 'AWS Certified Machine Learning - Sp...,"[{'name': 'English', 'proficiency': 'Native'},...",1053,3,"[{'post_id': 'urn:li:ugcPost:1111111', 'conten...",John,...,94043,"Mountain View, California",Experienced Data Scientist with a passion for ...,"[{'title': 'Senior Data Scientist', 'company':...","[{'schoolName': 'Stanford University', 'degree...",[{'name': {'localized': {'en_US': 'Machine Lea...,472,83,36,NaN
1,8923110b-1554-4a4c-be20-1deb2e232103,NaN,NaN,Information Technology & Services,[{'name': 'AWS Certified Machine Learning – Sp...,"[{'name': 'English', 'proficiency': 'Native'},...",1890,2,"[{'post_id': 'urn:li:ugcPost:3350334', 'conten...",Amanda,...,45211,"South Joel, Connecticut",NaN,"[{'title': 'Software Developer', 'company': {'...","[{'schoolName': 'MIT', 'degreeName': 'Master o...",[{'name': {'localized': {'en_US': 'Data Visual...,724,85,47,Wish bar above medical role defense task. Fath...
2,8923110b-1554-4a4c-be20-1deb2e232103,NaN,https://www.linkedin.com/in/amanda-gonzalez-89...,Information Technology & Services,[{'name': 'AWS Certified Machine Learning – Sp...,"[{'name': 'English', 'proficiency': 'Native'},...",1890,2,"[{'post_id': 'urn:li:ugcPost:3350334', 'conten...",Amanda,...,45211,"South Joel, Connecticut",NaN,"[{'title': 'Software Developer', 'company': {'...","[{'schoolName': 'MIT', 'degreeName': 'Master o...",[{'name': {'localized': {'en_US': 'Data Visual...,724,85,47,Wish bar above medical role defense task. Fath...

In [3]:
# Data Cleaning
df_profiles['location'] = df_profiles.apply(lambda row: {'location.postalCode': row['location.postalCode'], 'location.geographicArea': row['location.geographicArea']}, axis=1)

df_profiles['posts_summary']=df_profiles.apply(lambda row: {'total_posts':row['total_posts'],'total_likes':row['posts_summary.total_likes'],'total_comments':row['posts_summary.total_comments'],'total_shares':row['posts_summary.total_shares']},axis=1)
df_profiles['fullName']= df_profiles['firstName.localized.en_US'] + ' ' + df_profiles['lastName.localized.en_US']
df_profiles.columns

Index(['id', 'vanityName', 'publicProfileUrl', 'industry', 'certifications',
       'languages', 'followers', 'total_posts', 'posts',
       'firstName.localized.en_US', 'lastName.localized.en_US',
       'profilePicture.displayImage', 'headline.localized.en_US',
       'location.country', 'location.postalCode', 'location.geographicArea',
       'summary.localized.en_US', 'positions.elements', 'education.elements',
       'skills.elements', 'posts_summary.total_likes',
       'posts_summary.total_comments', 'posts_summary.total_shares', 'summary',
       'location', 'posts_summary', 'fullName'],
      dtype='object')

In [4]:
# Making a new clean dataset with well formated and relevant information
profiles_data=df_profiles[['id','firstName.localized.en_US','lastName.localized.en_US','fullName','publicProfileUrl','headline.localized.en_US','industry','summary','location','education.elements','certifications','positions.elements','skills.elements','followers','posts','posts_summary']]

profiles_data

,id,firstName.localized.en_US,lastName.localized.en_US,fullName,publicProfileUrl,headline.localized.en_US,industry,summary,location,education.elements,certifications,positions.elements,skills.elements,followers,posts,posts_summary
0,abcdef123456,John,Doe,John Doe,https://www.linkedin.com/in/john-doe,Senior Data Scientist at Google,Information Technology & Services,NaN,"{'location.postalCode': '94043', 'location.geo...","[{'schoolName': 'Stanford University', 'degree...",[{'name': 'AWS Certified Machine Learning - Sp...,"[{'title': 'Senior Data Scientist', 'company':...",[{'name': {'localized': {'en_US': 'Machine Lea...,1053,"[{'post_id': 'urn:li:ugcPost:1111111', 'conten...","{'total_posts': 3, 'total_likes': 472, 'total_..."
1,8923110b-1554-4a4c-be20-1deb2e232103,Amanda,Gonzalez,Amanda Gonzalez,NaN,Data Analyst,Information Technology & Services,Wish bar above medical role defense task. Fath...,"{'location.postalCode': '45211', 'location.geo...","[{'schoolName': 'MIT', 'degreeName': 'Master o...",[{'name': 'AWS Certified Machine Learning – Sp...,"[{'title': 'Software Developer', 'company': {'...",[{'name': {'localized': {'en_US': 'Data Visual...,1890,"[{'post_id': 'urn:li:ugcPost:3350334', 'conten...","{'total_posts': 2, 'total_likes': 724, 'total_..."
2,8923110b-1554-4a4c-be20-1deb2e232103,Amanda,Gonzalez,Amanda Gonzalez,https://www.linkedin.com/in/amanda-gonzalez-89...,Data Analyst,Information Technology & Services,Wish bar above medical role defense task. Fath...,"{'location.postalCode': '45211', 'location.geo...","[{'schoolName': 'MIT', 'degreeName': 'Master o...",[{'name': 'AWS Certified Machine Learning – Sp...,"[{'title': 'Software Developer', 'company': {'...",[{'name': {'localized': {'en_US': 'Data Visual...,1890,"[{'post_id': 'urn:li:ugcPost:3350334', 'conten...","{'total_posts': 2, 'total_likes': 724, 'total_..."

In [5]:
# Renaming columns for effeciency
profiles_data=profiles_data.rename(columns={'firstName.localized.en_US':'firstName','lastName.localized.en_US':'lastName','headline.localized.en_US':'headline','education.elemets':'education','positions.elements':'work_exp','skills.elements':'skills'})
profiles_data

,id,firstName,lastName,fullName,publicProfileUrl,headline,industry,summary,location,education.elements,certifications,work_exp,skills,followers,posts,posts_summary
0,abcdef123456,John,Doe,John Doe,https://www.linkedin.com/in/john-doe,Senior Data Scientist at Google,Information Technology & Services,NaN,"{'location.postalCode': '94043', 'location.geo...","[{'schoolName': 'Stanford University', 'degree...",[{'name': 'AWS Certified Machine Learning - Sp...,"[{'title': 'Senior Data Scientist', 'company':...",[{'name': {'localized': {'en_US': 'Machine Lea...,1053,"[{'post_id': 'urn:li:ugcPost:1111111', 'conten...","{'total_posts': 3, 'total_likes': 472, 'total_..."
1,8923110b-1554-4a4c-be20-1deb2e232103,Amanda,Gonzalez,Amanda Gonzalez,NaN,Data Analyst,Information Technology & Services,Wish bar above medical role defense task. Fath...,"{'location.postalCode': '45211', 'location.geo...","[{'schoolName': 'MIT', 'degreeName': 'Master o...",[{'name': 'AWS Certified Machine Learning – Sp...,"[{'title': 'Software Developer', 'company': {'...",[{'name': {'localized': {'en_US': 'Data Visual...,1890,"[{'post_id': 'urn:li:ugcPost:3350334', 'conten...","{'total_posts': 2, 'total_likes': 724, 'total_..."
2,8923110b-1554-4a4c-be20-1deb2e232103,Amanda,Gonzalez,Amanda Gonzalez,https://www.linkedin.com/in/amanda-gonzalez-89...,Data Analyst,Information Technology & Services,Wish bar above medical role defense task. Fath...,"{'location.postalCode': '45211', 'location.geo...","[{'schoolName': 'MIT', 'degreeName': 'Master o...",[{'name': 'AWS Certified Machine Learning – Sp...,"[{'title': 'Software Developer', 'company': {'...",[{'name': {'localized': {'en_US': 'Data Visual...,1890,"[{'post_id': 'urn:li:ugcPost:3350334', 'conten...","{'total_posts': 2, 'total_likes': 724, 'total_..."

In [6]:


df = pd.json_normalize(
    data,
    record_path=['posts'],  # Explodes the posts
    meta=[
        ['firstName', 'localized', 'en_US'],
        ['lastName', 'localized', 'en_US'],
        ['headline', 'localized', 'en_US'],
        'total_posts',
        ['posts_summary', 'total_likes'],
        ['posts_summary', 'total_comments'],
        ['posts_summary', 'total_shares']
    ],
    errors='ignore'
)

# Rename columns for clarity
df.rename(columns={
    'firstName.localized.en_US': 'First Name',
    'lastName.localized.en_US': 'Last Name',
    'headline.localized.en_US': 'Job Title',
    'content': 'Post Content',
    'likes': 'Likes',
    'comments': 'Comments',
    'shares': 'Shares',
    'post_url': 'Post URL'
}, inplace=True)

# Display
print(df[['First Name', 'Last Name', 'Job Title', 'Post Content', 'Likes', 'Comments', 'Shares']].head())

  First Name Last Name                        Job Title  \
0       John       Doe  Senior Data Scientist at Google
1       John       Doe  Senior Data Scientist at Google
2       John       Doe  Senior Data Scientist at Google
3     Amanda  Gonzalez                     Data Analyst
4     Amanda  Gonzalez                     Data Analyst

                                        Post Content  Likes  Comments  Shares
0  Excited to speak at the AI in Healthcare Summi...    153        24      12
1  Just published a blog on building secure ML pi...     88        17       5
2  Grateful to have completed my first year at NY...    231        42      19
3  Soldier example outside society institution lose.    212        49      10
4                    Majority civil set too defense.    107        19      11

In [7]:
df.to_csv('linkedin_profiles_posts.csv', index=False)

Calculate Similarity between keywords and post caption.---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

1. Preprocess Both Texts

In [22]:
# Clean and normalize both the employee summary and the job description.
import re
# python -m spacy download en_core_web_md
import spacy
nlp = spacy.load("en_core_web_md")
def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    return text

candidate_text = "I am a data scientist with 3 years of experience in Python, SQL, and machine learning. I deployed models using AWS."

result = preprocess(candidate_text)
print(result)

i am a data scientist with 3 years of experience in python sql and machine learning i deployed models using aws

2. Generate Embeddings

In [9]:
# Use NLP models like spaCy, Sentence-BERT, or OpenAI embeddings to get vector representations of both texts.
# Option A: Using spaCy (quick and easy)

# def get_spacy_similarity(text1, text2):
#     doc1 = nlp(preprocess(text1))
#     doc2 = nlp(preprocess(text2))
#     return doc1.similarity(doc2)  # returns a value between 0 and 1

In [10]:
# Option B: Using Sentence-BERT (more accurate for longer texts)
# 
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')

def get_bert_similarity(text1, text2):
    embeddings = model.encode([text1, text2], convert_to_tensor=True)
    return float(util.pytorch_cos_sim(embeddings[0], embeddings[1]))

In [ ]:
text1="Excited to speak at the AI in Summit next week!"
text2="We need a highly skilled individual with 5+ years of experience in training AI and ML models for healthcare Industry with skills like teamwork,leadership,accountibility,puntual,problemsolving skills,etc."
print(get_bert_similarity(text1,text2))

0.29278531670570374

:

3. Optional: Include Keyword-Based Boost

In [ ]:
#Create a list of must-have keywords/skills from the job description. Boost score based on keyword overlap with employee summary.

def keyword_boost(text1, text2, keywords):
    count = sum(1 for kw in keywords if kw.lower() in text1.lower() and kw.lower() in text2.lower())
    return count / len(keywords)  # normalized boost factor

In [ ]:
# Combine Semantic + Keyword Score (Optional Hybrid Model)
def final_similarity_score(summary, job_desc, keywords=[]):
    sim_score = get_bert_similarity(summary, job_desc)
    boost = keyword_boost(summary, job_desc, keywords)
    return round(0.8 * sim_score + 0.2 * boost, 3)

✅ Output Format
Similarity score (e.g., 0.82)

Match level:

0.8+ = Excellent match

0.6–0.79 = Good match

0.4–0.59 = Fair match

<0.4 = Weak match

_____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

In [11]:
from sentence_transformers import SentenceTransformer, util
from transformers import pipeline

In [13]:

# Load models
sbert_model = SentenceTransformer('all-MiniLM-L6-v2')
nli_model = pipeline("text-classification", model="roberta-large-mnli")

def combined_similarity(text1, text2, sbert_threshold=0.5):
    # Step 1: SBERT similarity
    embeddings = sbert_model.encode([text1, text2], convert_to_tensor=True)
    sim_score = float(util.pytorch_cos_sim(embeddings[0], embeddings[1]))

    # If similarity is low, no need to do NLI
    if sim_score < sbert_threshold:
        return {"similarity": sim_score, "relation": "unrelated"}

    # Step 2: Run NLI for sentence relationship
    nli_input = f"{text1} </s></s> {text2}"
    nli_result = nli_model(nli_input)[0]

    return {
        "similarity": sim_score,
        "relation": nli_result['label'],  # ENT, CON, NEUTRAL
        "confidence": nli_result['score']
    }

config.json:   0%|          | 0.00/688 [00:00<?, ?B/s]

d:\08-Softwares\Python\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\smitt\.cache\huggingface\hub\models--roberta-large-mnli. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/1.43G [00:00<?, ?B/s]

Some weights of the model checkpoint at roberta-large-mnli were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cpu

In [16]:
# Example
# text1 = "I love playing Valorant"
# text2 = "I hate playing Valorant"
# text1 = "The candidate has 5 years of experience in Python and machine learning."

# text2 = "The candidate has no experience in Python or machine learning."

text1 = "The customer received a full refund for the defective product."

text2 = "A complete refund was issued to the customer because the product was faulty."
result = combined_similarity(text1, text2)
print(result)

{'similarity': 0.8626693487167358, 'relation': 'ENTAILMENT', 'confidence': 0.9942692518234253}

In [18]:
from sentence_transformers import SentenceTransformer, util
from transformers import pipeline
import spacy
# python -m spacy download en_core_web_sm

# Load models
sbert_model = SentenceTransformer("all-MiniLM-L6-v2")
nli_model = pipeline("text-classification", model="roberta-large-mnli")
nlp = spacy.load("en_core_web_sm")

# Simple skill extractor using SpaCy
def extract_skills(text, keywords):
    doc = nlp(text.lower())
    found = set()
    for token in doc:
        if token.text in keywords:
            found.add(token.text)
    return found

# Match score calculator
def get_match_score(candidate_text, job_text, known_skills):
    # 1. Skill overlap
    cand_skills = extract_skills(candidate_text, known_skills)
    job_skills = extract_skills(job_text, known_skills)
    overlap = cand_skills.intersection(job_skills)
    skill_score = len(overlap) / len(job_skills) if job_skills else 0

    # 2. Semantic similarity
    embeddings = sbert_model.encode([candidate_text, job_text], convert_to_tensor=True)
    sim_score = float(util.pytorch_cos_sim(embeddings[0], embeddings[1]))

    # 3. NLI relationship
    relation = nli_model(f"{candidate_text} </s></s> {job_text}")[0]
    nli_bonus = 1.0 if relation['label'] == 'ENTAILMENT' else 0.5 if relation['label'] == 'NEUTRAL' else 0

    # Final weighted score (out of 100)
    final_score = (skill_score * 40) + (sim_score * 40) + (nli_bonus * 20)
    return round(final_score, 2), {
        "skills_matched": list(overlap),
        "semantic_score": round(sim_score, 2),
        "nli_relation": relation['label']
    }

Some weights of the model checkpoint at roberta-large-mnli were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

Sample 1

In [19]:
candidate_text = "I am a data scientist with 3 years of experience in Python, SQL, and machine learning. I deployed models using AWS."
job_text = "Looking for a machine learning engineer with experience in Python, SQL, AWS, and model deployment."

known_skills = {"python", "sql", "aws", "machine learning", "model deployment", "pandas", "scikit-learn"}

score, details = get_match_score(candidate_text, job_text, known_skills)

print("Match Score:", score)
print("Details:", details)

Match Score: 77.48
Details: {'skills_matched': ['sql', 'python', 'aws'], 'semantic_score': 0.69, 'nli_relation': 'NEUTRAL'}

Sample 2

In [21]:
#candidate_text = "I am a data scientist with 3 years of experience in Python, SQL, and machine learning. I deployed models using AWS."
#job_text = "Looking for a machine learning engineer with experience in Python, SQL, AWS, and model deployment."
candidate_text="Excited to speak at the AI in Summit next week!"
job_text="We need a highly skilled individual with 5+ years of experience in training AI and ML models for healthcare Industry with skills like teamwork,leadership,accountibility,puntual,problemsolving skills,etc."

known_skills = {"machine learning", "AI","ML"}

score, details = get_match_score(candidate_text, job_text, known_skills)

print("Match Score:", score)
print("Details:", details)

Match Score: 21.71
Details: {'skills_matched': [], 'semantic_score': 0.29, 'nli_relation': 'NEUTRAL'}