In [1]:
import numpy as np
import pandas as pd
import json

In [2]:
# Load the JSON file
with open('linkedIn_data.json', 'r') as file:
    data = json.load(file)

# Flatten and normalize nested JSON structures
df_profiles = pd.json_normalize(data)

# Show the first few rows
print(df_profiles.head())
df_profiles

             id vanityName                      publicProfileUrl  \
0  abcdef123456   john-doe  https://www.linkedin.com/in/john-doe
1  abcdef123456   john-doe  https://www.linkedin.com/in/john-doe

                            industry  \
0  Information Technology & Services
1  Information Technology & Services

                                      certifications  \
0  [{'name': 'AWS Certified Machine Learning - Sp...
1  [{'name': 'AWS Certified Machine Learning - Sp...

                                           languages  followers  total_posts  \
0  [{'name': 'English', 'proficiency': 'Native'},...       1053            3
1  [{'name': 'English', 'proficiency': 'Native'},...       1053            3

                                               posts  \
0  [{'post_id': 'urn:li:ugcPost:1111111', 'conten...
1  [{'post_id': 'urn:li:ugcPost:1111111', 'conten...

  firstName.localized.en_US  ... location.country location.postalCode  \
0                      John  ...               US               94043
1                    John-2  ...               US               94043

     location.geographicArea  \
0  Mountain View, California
1  Mountain View, California

                             summary.localized.en_US  \
0  Experienced Data Scientist with a passion for ...
1  Experienced Data Scientist with a passion for ...

                                  positions.elements  \
0  [{'title': 'Senior Data Scientist', 'company':...
1  [{'title': 'Senior Data Scientist', 'company':...

                                  education.elements  \
0  [{'schoolName': 'Stanford University', 'degree...
1  [{'schoolName': 'Stanford University', 'degree...

                                     skills.elements  \
0  [{'name': {'localized': {'en_US': 'Machine Lea...
1  [{'name': {'localized': {'en_US': 'Machine Lea...

  posts_summary.total_likes posts_summary.total_comments  \
0                       472                           83
1                       472                           83

  posts_summary.total_shares
0                         36
1                         36

[2 rows x 23 columns]

,id,vanityName,publicProfileUrl,industry,certifications,languages,followers,total_posts,posts,firstName.localized.en_US,...,location.country,location.postalCode,location.geographicArea,summary.localized.en_US,positions.elements,education.elements,skills.elements,posts_summary.total_likes,posts_summary.total_comments,posts_summary.total_shares
0,abcdef123456,john-doe,https://www.linkedin.com/in/john-doe,Information Technology & Services,[{'name': 'AWS Certified Machine Learning - Sp...,"[{'name': 'English', 'proficiency': 'Native'},...",1053,3,"[{'post_id': 'urn:li:ugcPost:1111111', 'conten...",John,...,US,94043,"Mountain View, California",Experienced Data Scientist with a passion for ...,"[{'title': 'Senior Data Scientist', 'company':...","[{'schoolName': 'Stanford University', 'degree...",[{'name': {'localized': {'en_US': 'Machine Lea...,472,83,36
1,abcdef123456,john-doe,https://www.linkedin.com/in/john-doe,Information Technology & Services,[{'name': 'AWS Certified Machine Learning - Sp...,"[{'name': 'English', 'proficiency': 'Native'},...",1053,3,"[{'post_id': 'urn:li:ugcPost:1111111', 'conten...",John-2,...,US,94043,"Mountain View, California",Experienced Data Scientist with a passion for ...,"[{'title': 'Senior Data Scientist', 'company':...","[{'schoolName': 'Stanford University', 'degree...",[{'name': {'localized': {'en_US': 'Machine Lea...,472,83,36

In [3]:
# Data Cleaning
df_profiles['location'] = df_profiles.apply(lambda row: {'location.postalCode': row['location.postalCode'], 'location.geographicArea': row['location.geographicArea']}, axis=1)

df_profiles['posts_summary']=df_profiles.apply(lambda row: {'total_posts':row['total_posts'],'total_likes':row['posts_summary.total_likes'],'total_comments':row['posts_summary.total_comments'],'total_shares':row['posts_summary.total_shares']},axis=1)
df_profiles['fullName']= df_profiles['firstName.localized.en_US'] + ' ' + df_profiles['lastName.localized.en_US']
df_profiles.columns

Index(['id', 'vanityName', 'publicProfileUrl', 'industry', 'certifications',
       'languages', 'followers', 'total_posts', 'posts',
       'firstName.localized.en_US', 'lastName.localized.en_US',
       'profilePicture.displayImage', 'headline.localized.en_US',
       'location.country', 'location.postalCode', 'location.geographicArea',
       'summary.localized.en_US', 'positions.elements', 'education.elements',
       'skills.elements', 'posts_summary.total_likes',
       'posts_summary.total_comments', 'posts_summary.total_shares',
       'location', 'posts_summary', 'fullName'],
      dtype='object')

In [4]:
# Making a new clean dataset with well formated and relevant information
profiles_data=df_profiles[['id','firstName.localized.en_US','lastName.localized.en_US','fullName','publicProfileUrl','headline.localized.en_US','industry','summary.localized.en_US','location','education.elements','certifications','positions.elements','skills.elements','followers','posts','posts_summary']]

profiles_data

,id,firstName.localized.en_US,lastName.localized.en_US,fullName,publicProfileUrl,headline.localized.en_US,industry,summary.localized.en_US,location,education.elements,certifications,positions.elements,skills.elements,followers,posts,posts_summary
0,abcdef123456,John,Doe,John Doe,https://www.linkedin.com/in/john-doe,Senior Data Scientist at Google,Information Technology & Services,Experienced Data Scientist with a passion for ...,"{'location.postalCode': '94043', 'location.geo...","[{'schoolName': 'Stanford University', 'degree...",[{'name': 'AWS Certified Machine Learning - Sp...,"[{'title': 'Senior Data Scientist', 'company':...",[{'name': {'localized': {'en_US': 'Machine Lea...,1053,"[{'post_id': 'urn:li:ugcPost:1111111', 'conten...","{'total_posts': 3, 'total_likes': 472, 'total_..."
1,abcdef123456,John-2,Doe-2,John-2 Doe-2,https://www.linkedin.com/in/john-doe,Senior Data Scientist at Google,Information Technology & Services,Experienced Data Scientist with a passion for ...,"{'location.postalCode': '94043', 'location.geo...","[{'schoolName': 'Stanford University', 'degree...",[{'name': 'AWS Certified Machine Learning - Sp...,"[{'title': 'Senior Data Scientist', 'company':...",[{'name': {'localized': {'en_US': 'Machine Lea...,1053,"[{'post_id': 'urn:li:ugcPost:1111111', 'conten...","{'total_posts': 3, 'total_likes': 472, 'total_..."

In [5]:
# Renaming columns for effeciency
profiles_data=profiles_data.rename(columns={'firstName.localized.en_US':'firstName','lastName.localized.en_US':'lastName','headline.localized.en_US':'headline','education.elemets':'education','positions.elements':'work_exp','skills.elements':'skills'})
profiles_data

,id,firstName,lastName,fullName,publicProfileUrl,headline,industry,summary.localized.en_US,location,education.elements,certifications,work_exp,skills,followers,posts,posts_summary
0,abcdef123456,John,Doe,John Doe,https://www.linkedin.com/in/john-doe,Senior Data Scientist at Google,Information Technology & Services,Experienced Data Scientist with a passion for ...,"{'location.postalCode': '94043', 'location.geo...","[{'schoolName': 'Stanford University', 'degree...",[{'name': 'AWS Certified Machine Learning - Sp...,"[{'title': 'Senior Data Scientist', 'company':...",[{'name': {'localized': {'en_US': 'Machine Lea...,1053,"[{'post_id': 'urn:li:ugcPost:1111111', 'conten...","{'total_posts': 3, 'total_likes': 472, 'total_..."
1,abcdef123456,John-2,Doe-2,John-2 Doe-2,https://www.linkedin.com/in/john-doe,Senior Data Scientist at Google,Information Technology & Services,Experienced Data Scientist with a passion for ...,"{'location.postalCode': '94043', 'location.geo...","[{'schoolName': 'Stanford University', 'degree...",[{'name': 'AWS Certified Machine Learning - Sp...,"[{'title': 'Senior Data Scientist', 'company':...",[{'name': {'localized': {'en_US': 'Machine Lea...,1053,"[{'post_id': 'urn:li:ugcPost:1111111', 'conten...","{'total_posts': 3, 'total_likes': 472, 'total_..."

In [6]:
#Post Analysis

df = pd.json_normalize(
    data,
    record_path=['posts'],  # Explodes the posts
    meta=[
        ['firstName', 'localized', 'en_US'],
        ['lastName', 'localized', 'en_US'],
        ['headline', 'localized', 'en_US'],
        'total_posts',
        ['posts_summary', 'total_likes'],
        ['posts_summary', 'total_comments'],
        ['posts_summary', 'total_shares']
    ],
    errors='ignore'
)

# Rename columns for clarity
df.rename(columns={
    'firstName.localized.en_US': 'First Name',
    'lastName.localized.en_US': 'Last Name',
    'headline.localized.en_US': 'Job Title',
    'content': 'Post Content',
    'likes': 'Likes',
    'comments': 'Comments',
    'shares': 'Shares',
    'post_url': 'Post URL'
}, inplace=True)

# Display
#df[['First Name', 'Last Name', 'Job Title', 'Post Content', 'Likes', 'Comments', 'Shares']].head()

df_posts=df[['First Name', 'Last Name', 'Job Title', 'Post Content', 'Likes', 'Comments', 'Shares']]
print(df_profiles)

             id vanityName                      publicProfileUrl  \
0  abcdef123456   john-doe  https://www.linkedin.com/in/john-doe
1  abcdef123456   john-doe  https://www.linkedin.com/in/john-doe

                            industry  \
0  Information Technology & Services
1  Information Technology & Services

                                      certifications  \
0  [{'name': 'AWS Certified Machine Learning - Sp...
1  [{'name': 'AWS Certified Machine Learning - Sp...

                                           languages  followers  total_posts  \
0  [{'name': 'English', 'proficiency': 'Native'},...       1053            3
1  [{'name': 'English', 'proficiency': 'Native'},...       1053            3

                                               posts  \
0  [{'post_id': 'urn:li:ugcPost:1111111', 'conten...
1  [{'post_id': 'urn:li:ugcPost:1111111', 'conten...

  firstName.localized.en_US  ...  \
0                      John  ...
1                    John-2  ...

                             summary.localized.en_US  \
0  Experienced Data Scientist with a passion for ...
1  Experienced Data Scientist with a passion for ...

                                  positions.elements  \
0  [{'title': 'Senior Data Scientist', 'company':...
1  [{'title': 'Senior Data Scientist', 'company':...

                                  education.elements  \
0  [{'schoolName': 'Stanford University', 'degree...
1  [{'schoolName': 'Stanford University', 'degree...

                                     skills.elements  \
0  [{'name': {'localized': {'en_US': 'Machine Lea...
1  [{'name': {'localized': {'en_US': 'Machine Lea...

  posts_summary.total_likes posts_summary.total_comments  \
0                       472                           83
1                       472                           83

  posts_summary.total_shares  \
0                         36
1                         36

                                            location  \
0  {'location.postalCode': '94043', 'location.geo...
1  {'location.postalCode': '94043', 'location.geo...

                                       posts_summary      fullName
0  {'total_posts': 3, 'total_likes': 472, 'total_...      John Doe
1  {'total_posts': 3, 'total_likes': 472, 'total_...  John-2 Doe-2

[2 rows x 26 columns]

In [9]:
#Post Analysis
clean_data=pd.DataFrame()
clean_data['id']=df_profiles['id']
clean_data['First Name']=df_profiles['firstName.localized.en_US']
clean_data['Last Name']=df_profiles['lastName.localized.en_US']
clean_data['Summary']=df_profiles['summary.localized.en_US']
clean_data['Industry']=df_profiles['industry']
clean_data['Posts']=df_profiles['posts']
clean_data['Qualifications']=df_profiles['education.elements']
clean_data['Certifications']=df_profiles['certifications']
clean_data['Experience']=df_profiles['positions.elements']
print(clean_data)

             id First Name Last Name  \
0  abcdef123456       John       Doe
1  abcdef123456     John-2     Doe-2

                                             Summary  \
0  Experienced Data Scientist with a passion for ...
1  Experienced Data Scientist with a passion for ...

                            Industry  \
0  Information Technology & Services
1  Information Technology & Services

                                               Posts  \
0  [{'post_id': 'urn:li:ugcPost:1111111', 'conten...
1  [{'post_id': 'urn:li:ugcPost:1111111', 'conten...

                                      Qualifications  \
0  [{'schoolName': 'Stanford University', 'degree...
1  [{'schoolName': 'Stanford University', 'degree...

                                      Certifications  \
0  [{'name': 'AWS Certified Machine Learning - Sp...
1  [{'name': 'AWS Certified Machine Learning - Sp...

                                          Experience
0  [{'title': 'Senior Data Scientist', 'company':...
1  [{'title': 'Senior Data Scientist', 'company':...

In [ ]:
def final_similarity_score(text1,text2,keyword):
    print()
def engagement_analysis(comments,likes,share):
    print()
def get_match_score(candidate_text, job_text, job_skills):
    print()
#looping all canditates
for i in range(len(clean_data)):
    posts=clean_data.iloc[i].Posts
    post_summary_score
    engagement_score
    Candidate_text=clean_data.iloc[i].Summary
    Job_text=''
    Job_req_skills = keyword_extraction_yake(){"python", "sql", "aws", "machine learning", "model deployment", "pandas", "scikit-learn"}
    Emp_descrip_score, details = get_match_score(Candidate_text, Job_text, Job_req_skills)
    
    #single candidates post evaluation
    for post in posts:
        content=post['content']
        comments=post['comments']
        likes=post['likes']
        shares=post['shares']
        post_summary_score=final_similarity_score(content,JD,keyword)
        engagement_score=engagement_analysis(comments,likes,shares)

Experienced Data Scientist with a passion for AI, ML, and large-scale data systems.
Experienced Data Scientist with a passion for AI, ML, and large-scale data systems.